// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2jx8Idd75PYPX6SNGtDtkHFlsEXd8cp8',
    appId: '1:912465144068:web:3d2a3f84b7239d6c2c4851',
    messagingSenderId: '912465144068',
    projectId: 'nexo-app-132da',
    authDomain: 'nexo-app-132da.firebaseapp.com',
    storageBucket: 'nexo-app-132da.appspot.com',
    measurementId: 'G-3FHXXH4R23',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWzyQmhgbgk1H3NNxgTI7zowiPx6F3qlQ',
    appId: '1:912465144068:android:ce50a774d67b3a832c4851',
    messagingSenderId: '912465144068',
    projectId: 'nexo-app-132da',
    storageBucket: 'nexo-app-132da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg08FHzwmEdmVQmIApJzFdz96PSLUHBDU',
    appId: '1:912465144068:ios:875974c60bd410e32c4851',
    messagingSenderId: '912465144068',
    projectId: 'nexo-app-132da',
    storageBucket: 'nexo-app-132da.appspot.com',
    iosClientId: '912465144068-7skj0ebcpofmfqaa5ra2rho91nh30ocp.apps.googleusercontent.com',
    iosBundleId: 'com.example.nexoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBg08FHzwmEdmVQmIApJzFdz96PSLUHBDU',
    appId: '1:912465144068:ios:17f998ad4e2676042c4851',
    messagingSenderId: '912465144068',
    projectId: 'nexo-app-132da',
    storageBucket: 'nexo-app-132da.appspot.com',
    iosClientId: '912465144068-n59t3all6bj54htteqj5gttulo1q4cv3.apps.googleusercontent.com',
    iosBundleId: 'com.example.nexoApp.RunnerTests',
  );
}
